### ISSUE TITLE
MiniDLNA is already running

### ISSUE THREAD

**Issue by DavHau** [geekduck/docker-minidlna#3]
Since recently the container stopped working without me changing any settings. It crashes on start right away stating:

minidlna.c:961: error: MiniDLNA is already running. EXITING.

**Comment by aborovsky** [comment]
+1

**Comment by aborovsky** [comment]
This manual action will help: https://forums.unraid.net/topic/44138-support-binhex-minidlna/page/3/?tab=comments#comment-563019

`docker exec -it geekduck/minidlna rm /run/minidlna/minidlna.pid`
